spring.application.name=s19challenge-twitter
spring.datasource.url=jdbc:postgresql://localhost:5432/fsweb
spring.datasource.username=postgres
spring.datasource.password=Malmsteen1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=3000
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
server.servlet.context-path=/

logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE
logging.level.org.springframework.security=DEBUG
logging.level.com.workintech=DEBUG
logging.level.org.springframework.security.web=DEBUG

